### ISSUE TITLE
Feature: User can enter address

### ISSUE THREAD

**Issue by GiancarloMassoni** [GiancarloMassoni/healthy-hacks#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to enter an address
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to view the home screen and input an address.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71737839/209996404-d95f5d9f-db21-46dd-b4e1-ab730500f264.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component for the html skeleton and header
- [x] Create a search bar and button 
- [x] Create a home button that switches to the home view
- [x] create css and layout classes
- [x] take the user input and translate the address to longitude and latitude values

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
