### ISSUE TITLE
Feature: User can view restaurants near address

### ISSUE THREAD

**Issue by GiancarloMassoni** [GiancarloMassoni/healthy-hacks#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search address to view nearby restaurants
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to type in an address and find the nearest restaurants in the vicinity
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71737839/210408062-2e40ee50-76d8-49fa-9eac-dcc46ce13ee9.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Fetch nearest restaurants using nutrionix api
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Store the longitude and latitude in variable in order to create a fetch request on nutrionix API
- [x] Create a fetch request using the longitude and latitude of the user entered address
- [x] Store and display the nearest restaurants with logos and a link to the menu
- [x] Update component home to add restaurants in the vicinity of the user entered address
- [ ] 

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
