### ISSUE TITLE
Feature: User can add favorite restaurants

### ISSUE THREAD

**Issue by GiancarloMassoni** [GiancarloMassoni/healthy-hacks#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add favorite restaurants 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71737839/211078729-0edbf38a-0849-4c34-9815-35c13ecde5af.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...
- [ ]  When user adds restaurant to favorite make a query sending the name of the restaurant to the database and add it to the restaurants table

### ☁️ Server Tasks

- [ ] Update `server/index.js` to make post to the api of restaurants table and add whichever table is favorited from user
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Update component to add a new button labeled favorite
- [ ] the button when pressed should send the current restaurant name to the back end where it adds the restaurant to the restaurant table.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
