### ISSUE TITLE
Feature: User can favorite meals

### ISSUE THREAD

**Issue by GiancarloMassoni** [GiancarloMassoni/healthy-hacks#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add favorite meals
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71737839/212415090-07248206-7109-4e86-8c9e-a518373a12e0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Make a sql query to send the favorite meal information

### ⚡ Client Tasks

- [x] Update component to have a favorite button for each meal and when the button is pressed it sends a fetch request to the database and sends the info of the meal and stores it in the table with the current user.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
